README and misc updates
OpenPerpetuum/PerpetuumServer pull request #101
Opened 2019-05-13 02:04 UTC by MikeJeffers

2019-05-15 16:46 UTC, clouths submitted a review, later dismissed
I approve.

2019-05-16 11:48 UTC, nref-dan requested changes
Line 17 is problematic and needs changing. Also the README is detected as a binary file. It might be worth deleting your local and typing it out on Notepad in ASCII mode. Possible hidden Unicode character, as I'm unsure why else it would think that.

Final point, I think we should include some basic build/startup instructions in the README. At the very least, a list of tools/frameworks needed to build/F5 the project.

2019-05-16 11:48 UTC, Ketsuekiame commented on CONTRIBUTING.md
> + - Be either ungrokable, insufficiently documented (self-/comments) or otherwise unmaintainable by other experienced developers.
Ummm, I think you mean the opposite :D

2019-05-16 11:48 UTC, Ketsuekiame commented on CONTRIBUTING.md
> + - Be either ungrokable, insufficiently documented (self-/comments) or otherwise unmaintainable by other experienced developers.
Also, Grok, really? 😛

2019-05-17 01:22 UTC, MikeJeffers commented
> 
> 
> Line 17 is problematic and needs changing. Also the README is detected as a binary file. It might be worth deleting your local and typing it out on Notepad in ASCII mode. Possible hidden Unicode character, as I'm unsure why else it would think that.
> 
> Final point, I think we should include some basic build/startup instructions in the README. At the very least, a list of tools/frameworks needed to build/F5 the project.

Totally agree, please add and improve this!  I am just trying to kick-start some documentation and clarifying text to get people oriented at least.

2019-06-02 23:40 UTC, MikeJeffers commented
@Ketsuekiame need re-review before we can merge

2019-06-04 02:12 UTC, clouths submitted a review, later dismissed
I approve this update!
Also the content on the website seems excellent so far, other than maybe adding the links on the navigation page, everything is fine!

2019-06-06 07:37 UTC, Ketsuekiame commented on CONTRIBUTING.md
> +As mentioned above, all action items are collected in one kanban board for Server related development.  These issues should be pointed to with all PR's made.  A PR should address at most one OP-Proje
issue tool*

2019-06-06 07:41 UTC, nref-dan requested changes
I'm also going to need to change the readme file manually because github sees it as a binary file and won't let me review it.

2019-06-08 13:28 UTC, nref-dan approved these changes

2019-06-08 18:09 UTC, merged