Relics
OpenPerpetuum/PerpetuumServer pull request #91
Opened 2019-01-12 04:37 UTC by MikeJeffers

Relics
Bloody Relics

2019-01-12 04:41 UTC, MikeJeffers commented
Some test SQL if you would like to test locally:
```
USE [perpetuumsa]
GO



DROP TABLE IF EXISTS dbo.relics;
DROP TABLE IF EXISTS dbo.relicloots;
DROP TABLE IF EXISTS dbo.relicspawninfos;
DROP TABLE IF EXISTS dbo.relicinfos;
DROP TABLE IF EXISTS dbo.reliczoneconfigs;



CREATE TABLE dbo.relics(
id INT NOT NULL IDENTITY PRIMARY KEY,
relicinfoid INT NOT NULL,
zoneid INT NOT NULL,
x INT NOT NULL,
y INT NOT NULL
);

CREATE TABLE dbo.relicinfos(
id INT NOT NULL IDENTITY PRIMARY KEY,
name VARCHAR(128) NOT NULL,
goalrange INT NOT NULL
);

CREATE TABLE dbo.relicloots(
id INT NOT NULL IDENTITY PRIMARY KEY,
definition INT NOT NULL,
minquantity INT NOT NULL,
maxquantity INT NOT NULL,
chance FLOAT NOT NULL,
relicinfoid INT NOT NULL,
packed BIT NOT NULL
);

CREATE TABLE dbo.relicspawninfos(
id INT NOT NULL IDENTITY PRIMARY KEY,
relicinfoid INT NOT NULL,
zoneid INT NOT NULL,
rate INT NOT NULL,
x INT NULL,
y INT NULL
);

CREATE TABLE dbo.reliczoneconfigs(
id INT NOT NULL IDENTITY PRIMARY KEY,
zoneid INT NOT NULL,
maxspawn INT NOT NULL,
respawnrate INT NOT NULL
);


--------------TEST STUFF--------

INSERT INTO dbo.reliczoneconfigs 
	([zoneid], [maxspawn], [respawnrate]) 
SELECT 
     zones.id, 55, 3600
FROM 
     dbo.zones
WHERE 
     zones.active=1 and zones.enabled=1

--Set some zones to have no natural spawning relics
UPDATE dbo.reliczoneconfigs SET
	maxspawn = 0
WHERE zoneid in (16, 45, 50, 51);


--Create different relic types
INSERT INTO [dbo].[relicinfos]
           ([name],[goalrange])
     VALUES
           ('test_relic',3),
		   ('test_static',3);

--Insert loots for each type
INSERT INTO [dbo].[relicloots]
           ([definition],[minquantity],[maxquantity],[chance],[relicinfoid],[packed])
     VALUES
           ((SELECT TOP 1 definition FROM entitydefaults WHERE definitionname='def_common_reactor_plasma')
           ,1
           ,1000
           ,1.0
           ,(SELECT TOP 1 id FROM relicinfos WHERE name='test_relic')
           ,1),
		   ((SELECT TOP 1 definition FROM entitydefaults WHERE definitionname='def_kernel_common')
           ,1
           ,1000
           ,1.0
           ,(SELECT TOP 1 id FROM relicinfos WHERE name='test_static')
           ,1);
GO

DECLARE @relicinfoID int;
SET @relicinfoID = (SELECT TOP 1 id FROM relicinfos WHERE name='test_relic')
INSERT INTO [dbo].[relicspawninfos]
           ([relicinfoid],[zoneid],[rate],[x],[y])
SELECT 
	@relicinfoID, [zoneid], 20, NULL, NULL
FROM
	dbo.reliczoneconfigs

--insert static
INSERT INTO [dbo].[relicspawninfos]
           ([relicinfoid],[zoneid],[rate],[x],[y])
		   VALUES
		   ((SELECT TOP 1 id FROM relicinfos WHERE name='test_static'),
		   8,
		   5,
		   920,
		   820);
GO
```

2019-02-03 09:39 UTC, nref-dan reviewed
1. Why the change of lock types?
2. Why are we locking entire methods?

2019-02-03 10:01 UTC, nref-dan commented on src/Perpetuum/Services/Relics/RelicManager.cs
> +                foreach (var r in _relicsOnZone)
This whole loop can be simplified to 
```
while (_relicsOnZone.Any(r => RESPAWN_PROXIMITY > pt.Distance(r.GetPosition)))
{
  pt = _spawnPosFinder.FindSpawnPosition();
  attempts++;

  if (attempts > maxAttempts)
  {
    Logger.Error("Could not get Position for next Relic on Zone: " + _zone.Id);
    return;
  }
}
```
As this no longer has three self-managed points of flow control.

2019-02-03 10:01 UTC, nref-dan commented on src/Perpetuum/Services/Relics/RelicManager.cs
> +                    foreach (var r in _relicsOnZone)
This appears to be the same check as my comment below. Use the LINQ statement instead.

I'm also not sure we want to be "dumping" the generated relic either as this can affect the expected spawn rates.

Additionally, GetNextRelicInfo always returns the first relic in the list that matches the "chance" condition. Unless they are ordered by "spawn chance" ascending it's entirely possible you will always see one type of relic. If the order is random, then beware, cos here be dragons...

2019-02-25 03:07 UTC, MikeJeffers commented
@Ketsuekiame @LoyalServant Ready for another Review pass!
Note you will need https://github.com/OpenPerpetuum/OPDB/pull/116 run on your DB 
It will be inserting a dummy EntityDefault - which is required for making a valid Unit for the Zone

2019-03-13 22:42 UTC, LoyalServant submitted a review, later dismissed

2019-04-05 09:18 UTC, nref-dan requested changes

2019-04-05 09:18 UTC, Ketsuekiame commented on src/Perpetuum/Services/Relics/Relic.cs
> +        private ReaderWriterLockSlim _lifespanLock;
Can we add a warning to this file to never cross the ~streams~ locks

2019-04-05 10:15 UTC, nref-dan requested changes

2019-04-05 10:15 UTC, nref-dan commented on src/Perpetuum.Bootstrapper/PerpetuumBootstrapper.cs
> +                    var numRelicConfigs = Db.Query().CommandText("SELECT * FROM relicspawninfo WHERE zoneid = @zoneId")
Please don't use select *. For example, I can't see at a glance what data this is working with. Also, it can lead to errors where the name of the field changes and we don't know until it stops working in live.

2019-04-05 10:15 UTC, nref-dan commented on src/Perpetuum.Bootstrapper/PerpetuumBootstrapper.cs
> +                    var zoneConfigs = Db.Query().CommandText("SELECT * FROM reliczoneconfig WHERE zoneid = @zoneId")
Please don't use select *. For example, I can't see at a glance what data this is working with. Also, it can lead to errors where the name of the field changes and we don't know until it stops working in live.

2019-04-05 10:15 UTC, nref-dan commented on src/Perpetuum.ExportedTypes/DefinitionNames.cs
> +         public const string RELIC = "def_relic";
What happened to the indentation here? XD

2019-04-05 10:15 UTC, nref-dan commented on src/Perpetuum/Services/Channels/GameAdminCommands.cs
> +                channel.SendMessageToAll(sessionManager, sender, "unlockallep: " + dictionary.ToDebugString());
Is this debug output being left in intentionally?

2019-04-05 10:15 UTC, nref-dan commented on src/Perpetuum/Services/Relics/RelicInfo.cs
> +            var info = relicinfos.ToList()[0];//TODO risky?
Call `.SingleOrDefault()`. This will return **the single entry** or null (in our case) if there are no entries. If there is more than one entry it will throw an exception. Given that your SQL calls 'top 1' you will have either 1 or 0 entries so I wouldn't worry about the exception case.

2019-04-05 10:15 UTC, nref-dan commented on src/Perpetuum/Services/Relics/RelicLoot.cs
> +            } while (result.Count < 1);
This can be changed to `while (!result.Any());`

The difference is that Count will do a count of every item in the list before returning (performing an iterator spin up). Any stops at the first item and returns via memory reference checking. In our case the performance difference is marginal because we will always have 0 unless existing the loop. But I prefer that standard.

2019-04-05 10:15 UTC, nref-dan commented on src/Perpetuum/Services/Relics/RelicLoot.cs
> +    public class RelicLootItems
Be extremely careful here; IEnumerable is a deferred execution provider. It doesn't "have" any data and only executes when you call a finaliser (like .ToList()).

Effectively you're only storing a query and not the actual object itself.

2019-04-05 10:15 UTC, nref-dan commented on src/Perpetuum/Services/Relics/RelicLoot.cs
> +            var resultList = new List<IRelicLoot>();
`resultList = loots.ToList();` ?

2019-04-05 10:15 UTC, nref-dan commented on src/Perpetuum/Services/Relics/RelicManager.cs
> +            using (_lock.Write(THREAD_TIMEOUT))
write lock on read?

2019-04-05 10:15 UTC, nref-dan commented on src/Perpetuum/Services/Relics/RelicManager.cs
> +            var list = new List<Dictionary<string, object>>();
```
using (_lock.Write(THREAD_TIMEOUT))
    return _relics.Select(r => r.ToDebugDictionary()).ToList();
```

2019-04-05 10:15 UTC, nref-dan commented on src/Perpetuum/Services/Relics/RelicManager.cs
> +            var list = new List<Dictionary<string, object>>();
Also, does this need a write lock? A read lock should suffice.

2019-04-05 10:15 UTC, Ketsuekiame commented on src/Perpetuum/Services/Relics/RelicSpawnInfo.cs
> +            var resultList = new List<RelicSpawnInfo>();
`var resultList = reliceZoneConfigs.ToList();` ?

2019-04-05 10:15 UTC, Ketsuekiame commented on src/Perpetuum/Services/Relics/RelicZoneConfig.cs
> +            var relicZoneConfigs = Db.Query().CommandText("SELECT TOP 1 id, zoneid, maxspawn, respawnrate FROM reliczoneconfig WHERE zoneid = @zoneId")
`return relicZoneConfigs.SingleOrDefault();`

2019-04-05 12:46 UTC, MikeJeffers commented on src/Perpetuum/Services/Channels/GameAdminCommands.cs
> +                channel.SendMessageToAll(sessionManager, sender, "unlockallep: " + dictionary.ToDebugString());
Yes - it was added as a way to confirm the command message went through.  its kind of worrisome as a user when you type the command and dont see any output, hard to verify if it worked or not.  Just a QoL thing and a way to double check you typed the right account etc..

2019-04-05 13:02 UTC, Ketsuekiame commented on src/Perpetuum/Services/Channels/GameAdminCommands.cs
> +                channel.SendMessageToAll(sessionManager, sender, "unlockallep: " + dictionary.ToDebugString());
Aight, just had to double check :)

2019-04-05 22:47 UTC, MikeJeffers commented on src/Perpetuum/Services/Relics/RelicLoot.cs
> +            } while (result.Count < 1);
Nice tip - will integrate (and use where I am checking empty lists more often!)

2019-04-05 23:47 UTC, MikeJeffers commented
@Ketsuekiame Changes addressed in full.  Did some load testing, thread pausing and other bits to ensure those read locks were safe.  Guess I just got too cautious with using reads.

2019-04-06 14:29 UTC, nref-dan approved these changes

2019-04-06 14:40 UTC, merged